version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-rc-stretch
    working_directory: ~/Done_api/
    steps:
    - checkout:
        path: ~/Done_api
    - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.6-rc-stretch
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
    environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        APP_DATABASE_HOST: "127.0.0.1"
        RAILS_ENV: test
    working_directory: ~/Done_api/
    steps:
      - checkout:
          path: ~/Done_api
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: rspec test
          command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
# テスト
