version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-rc-stretch
    working_directory: ~/Done_api/
    steps:
    - checkout:
        path: ~/Done_api
    - ruby/install-deps
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
